version: '3.8'

services:
  flaskapp:
    image: estebanmr30/bookstoreobjetive3:amd64
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5000:5000'
    networks:
      - bookstore_net

networks:
  bookstore_net:
    driver: overlay
