version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=production
      - DB_HOST=bookstoredb.c7hyjtnhxg7c.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_NAME=bookstoredb
      - DB_USER=admin
      - DB_PASSWORD=bookstoreDB
    ports:
      - "5000:5000"
    networks:
      - bookstore_net

networks:
  bookstore_net:
