version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - /mnt/efs:/app/uploads
    networks:
      - bookstore_net

networks:
  bookstore_net:
